# Generated by Django 4.2.2 on 2023-07-25 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usersettings_blog_is_changed_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
