# Generated by Django 4.2.3 on 2023-07-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_room_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='text',
        ),
    ]
