[tool.ruff]
# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.13
target-version = "py313"

# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default. 
lint.select = ["E", "F"]
lint.ignore = ["F403", "F401"]

# Allow autofix for all enabled rules (when `--fix`) is provided. 
lint.unfixable = []

exclude = [".git", ".ruff_cache", "__pypackages__", "build", "venv"]

# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.

# Allow fix for all enabled rules (when `--fix`) is provided.
lint.fixable = ["ALL"]

[tool.ruff.format]
# Like Black, indent with spaces, rather than tabs.
indent-style = "tab"

[tool.pytest.ini_options]
asyncio_mode = "auto"
