from app.views.blog import BlogAPIView
from app.views.chat import ChatAPIView
from app.views.find_user import FindUserAPIView
from app.views.friends import FriendsAPIView
from app.views.messages import MessagesAPIView
from app.views.news import NewsAPIView
from app.views.rooms import RoomsAPIView
from app.views.subscriber import SubscriberAPIView
from app.views.user import UserAPIView
