# Generated by Django 5.2.6 on 2025-10-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("app", "0002_alter_message_timestamp"),
	]

	operations = [
		migrations.AddField(
			model_name="user",
			name="user_timezone",
			field=models.CharField(
				blank=True, max_length=150, verbose_name="User timezone"
			),
		),
	]
