# Generated by Django 5.2.6 on 2025-09-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("app", "0002_alter_room_creator"),
	]

	operations = [
		migrations.AddField(
			model_name="user",
			name="ethereum_address",
			field=models.CharField(
				blank=True, max_length=150, verbose_name="ethereum address"
			),
		),
		migrations.AddField(
			model_name="user",
			name="infura_api_key",
			field=models.CharField(
				blank=True, max_length=150, verbose_name="infura api key"
			),
		),
	]
