# Generated by Django 5.2.6 on 2025-09-14 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("app", "0003_user_ethereum_address_user_infura_api_key"),
	]

	operations = [
		migrations.CreateModel(
			name="Transaction",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("timestamp", models.DateTimeField(auto_now_add=True)),
				("tx_hash", models.CharField(blank=True, max_length=1000)),
				("receipt", models.CharField(blank=True, max_length=1000)),
				("value", models.IntegerField(blank=True)),
				(
					"recipient",
					models.ForeignKey(
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name="transaction_recipient",
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					"sender",
					models.ForeignKey(
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name="transaction_sender",
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
		),
	]
