# Generated by Django 5.2.6 on 2025-10-04 22:21

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("app", "0003_user_user_timezone"),
	]

	operations = [
		migrations.AddField(
			model_name="user",
			name="image",
			field=models.FileField(
				blank=True,
				default=None,
				null=True,
				upload_to=app.models._directory_path_for_user,
			),
		),
	]
