# Generated by Django 5.2.6 on 2025-09-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("app", "0004_transaction"),
	]

	operations = [
		migrations.AddField(
			model_name="transaction",
			name="current_balance",
			field=models.IntegerField(blank=True, null=True),
		),
		migrations.AddField(
			model_name="transaction",
			name="gas_price",
			field=models.IntegerField(blank=True, null=True),
		),
	]
