# Generated by Django 5.1.6 on 2025-03-01 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_onlinestatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlinestatus',
            options={'verbose_name_plural': 'OnlineStatuses'},
        ),
    ]
