# Generated by Django 5.2.6 on 2025-10-05 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("app", "0004_user_image"),
	]

	operations = [
		migrations.AddField(
			model_name="message",
			name="parent",
			field=models.ForeignKey(
				blank=True,
				default=None,
				null=True,
				on_delete=django.db.models.deletion.SET_NULL,
				to="app.message",
			),
		),
	]
