# Generated by Django 5.2.6 on 2025-09-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_transaction_current_balance_transaction_gas_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='gas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
