# Generated by Django 5.1.7 on 2025-10-10 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("app", "0005_message_parent"),
	]

	operations = [
		migrations.CreateModel(
			name="MessageLike",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				(
					"message",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="message_like",
						to="app.message",
					),
				),
				(
					"user",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="user_like",
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
		),
	]
