# Generated by Django 5.1.6 on 2025-03-02 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_onlinestatus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlinestatus',
            options={'verbose_name_plural': 'Online Statuses'},
        ),
    ]
