# Generated by Django 5.2.6 on 2025-09-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("app", "0006_transaction_gas"),
		("auth", "0012_alter_user_first_name_max_length"),
	]

	operations = [
		migrations.RemoveIndex(
			model_name="post",
			name="app_post_user_id_06bc58_idx",
		),
		migrations.AddIndex(
			model_name="message",
			index=models.Index(fields=["id"], name="app_message_id_17d509_idx"),
		),
		migrations.AddIndex(
			model_name="post",
			index=models.Index(fields=["id"], name="app_post_id_2e2017_idx"),
		),
		migrations.AddIndex(
			model_name="post",
			index=models.Index(
				fields=["user_id", "timestamp"], name="app_post_user_id_78f9d3_idx"
			),
		),
		migrations.AddIndex(
			model_name="room",
			index=models.Index(fields=["id"], name="app_room_id_d7bfd2_idx"),
		),
		migrations.AddIndex(
			model_name="roominvitation",
			index=models.Index(fields=["id"], name="app_roominv_id_5a51c4_idx"),
		),
		migrations.AddIndex(
			model_name="roominvitation",
			index=models.Index(
				fields=["to_user_id"], name="app_roominv_to_user_24389e_idx"
			),
		),
		migrations.AddIndex(
			model_name="roominvitation",
			index=models.Index(
				fields=["room_id", "to_user_id"], name="app_roominv_room_id_dc5966_idx"
			),
		),
		migrations.AddIndex(
			model_name="transaction",
			index=models.Index(
				fields=["sender_id", "recipient_id", "timestamp"],
				name="app_transac_sender__ffe213_idx",
			),
		),
		migrations.AddIndex(
			model_name="user",
			index=models.Index(fields=["username"], name="app_user_usernam_f7396d_idx"),
		),
	]
