# Generated by Django 5.1.6 on 2025-03-06 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_blog_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['user_id'], name='app_subscri_user_id_3b55e4_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['subscribe_id'], name='app_subscri_subscri_bbe7f2_idx'),
        ),
    ]
