# Generated by Django 5.1.6 on 2025-03-06 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_subscriber_app_subscri_user_id_3b55e4_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room_id'], name='app_message_room_id_73e865_idx'),
        ),
        migrations.AddIndex(
            model_name='onlinestatus',
            index=models.Index(fields=['user_id'], name='app_onlines_user_id_3d071d_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user_id'], name='app_post_user_id_06bc58_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['user_id', 'subscribe_id'], name='app_subscri_user_id_2f7795_idx'),
        ),
    ]
