# Generated by Django 5.1.6 on 2025-03-08 15:03

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_message_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=app.models._user_directory_path),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, default=None, max_length=5000, null=True),
        ),
    ]
