from backend.api.views.blog import BlogAPIView
from backend.api.views.chat import ChatAPIView
from backend.api.views.find_user import FindUserAPIView
from backend.api.views.friends import FriendsAPIView
from backend.api.views.messages import MessagesAPIView
from backend.api.views.news import NewsAPIView
from backend.api.views.rooms import RoomsAPIView
from backend.api.views.subscriber import SubscriberAPIView
from backend.api.views.user import UserAPIView
