from api.views.blog import BlogAPIView
from api.views.chat import ChatAPIView
from api.views.find_user import FindUserAPIView
from api.views.friends import FriendsAPIView
from api.views.messages import MessagesAPIView
from api.views.news import NewsAPIView
from api.views.rooms import RoomsAPIView
from api.views.subscriber import SubscriberAPIView
from api.views.user import UserAPIView
